import Head from 'next/head'
import styles from '../../styles/Home.module.css' 
import Layout from '../../components/layout'
import Footer from '../../components/footer'
import Title from '../../components/title'
import Link from 'next/link';

export default function Users({users}){
	return(
        <div className={styles.container}>
			<Layout>
                <Title>Nosotros</Title>
            </Layout>
			<Head>
                <title>CREPSA: Consultoria contable, fiscal y digital para negocios</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
		 	<main>
				<p>Párrafo de prueba para la página nosotros</p>
				 <div className='grid'>
					{users.map(user =>{
							return(
								<Link href={'/users/[id]'} as={`/users/${user.id}`} key={user.id}>
									<a className='card'>
										<h3>User</h3>
										<p>Name: {user.name}</p>
										<p>Email: {user.email}</p>
									</a>
								</Link>
							)
					})}
				</div>
				<style jsx>
			{`
				.grid {
				display: flex;
				align-items: center;
				justify-content: center;
				flex-wrap: wrap;
				max-width: 800px;
				margin-top: 3rem;
				}
				.card {
				margin: 1rem;
				flex-basis: 45%;
				padding: 1.5rem;
				text-align: left;
				color: inherit;
				text-decoration: none;
				border: 1px solid #eaeaea;
				border-radius: 10px;
				transition: color 0.15s ease, border-color 0.15s ease;
				}
				.card:hover,
				.card:focus,
				.card:active {
				color: #0070f3;
				border-color: #0070f3;
				}
				.card h3 {
				margin: 0 0 1rem 0;
				font-size: 1.5rem;
				}
				.card p {
				margin: 0;
				font-size: 1.25rem;
				line-height: 1.5;
				}
				p{
					color: darkgray;
					}
					p:hover{
					color: red;
					}
			`}
			</style>
			 </main>
			 <Footer></Footer>

        	
        </div>
	)
}

export async function getStaticProps(){
	const res = await fetch('https://api.jsonbin.io/b/60fdc373a917050205d0233f');
	const users = await res.json();

	return{
		props:{
			users
		}
	}
}