import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Title from '../components/title'
import Layout from '../components/layout'
import Footer from '../components/footer'
export default function Contact() {
  return (
    <div className={styles.container}>
      <Layout>
        <Title>Contacto</Title>
      </Layout>
      <Head>
        <title>Página de contacto CREPSA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Contact Form
        </h1>

        <div className={styles.grid}>
          <form name="contact" method="POST" data-netlify="true" className={styles.card} >
            <input type="hidden" name="form-name" value="contact" />

              <p>
                  <label htmlFor="name">Nombre</label>
                  <input type="text" id="name" name="name" />
              </p>
              <p>
                  <label htmlFor="email">Email</label>
                  <input type="text" id="email" name="email" />
              </p>
              <p>
                  <label htmlFor="message">Mensaje</label>
                  <textarea id="message" name="message"></textarea>
              </p>
              <p>
                  <button type="submit">Send</button>
              </p>
              
          </form>
        </div>
      </main>

      <Footer></Footer> 
    </div>
  )
}
