import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Title from '../components/title'
import Footer from '../components/footer'
import Layout from '../components/layout'

export default function Services(){
    return(
        <div className={styles.container}>
        <Layout>
            <Title>Nosotros</Title>
        </Layout>
        <Head>
            <title>CREPSA: Consultoria contable, fiscal y digital para negocios</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <p>Párrafo de prueba para la página nosotros</p>
            <style>
            {`
                p{
                color: darkgray;
                }
                p:hover{
                color: red;
                }
            `}
            </style>
        </main>
        <Footer></Footer>
    </div>
    )
}