import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Title from '../components/title'
import Layout from '../components/layout'
import Footer from '../components/footer'

export default function Us({ playlistLists }){
    return(
        <div className={styles.container}>
            <Layout>
                <Title>Nosotros</Title>
            </Layout>
            <Head>
                <title>CREPSA: Consultoria contable, fiscal y digital para negocios</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <p>Párrafo de prueba para la página nosotros</p>
                <Heading mt={8} mb={4} fontWeight='800'>
                HipHop Playlist
                </Heading>
                <List>
                {playlistLists.map((playlistList) => (
                    <Song key={playlistList.id} {...playlistList} />
                ))}
                </List> 
                <style>
                {`
                    p{
                    color: darkgray;
                    }
                    p:hover{
                    color: red;
                    }
                `}
                </style>
            </main>
            <Footer></Footer>
        </div>
    )
}